<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <WarningsNotAsErrors>$(WarningsNotAsErrors);NU1903</WarningsNotAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Lexql.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime.Standard" Version="4.13.1" />
    <PackageReference Include="Antlr4BuildTasks" Version="12.8.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Antlr4 Include="..\..\grammar\MySqlLexer.g4">
      <Package>Lexql.Core.Relational.Sql.Antlr</Package>
      <Listener>false</Listener>
      <Visitor>false</Visitor>
    </Antlr4>
  </ItemGroup>

</Project>
